### ISSUE TITLE
trigger.change on number input throws a warning

### ISSUE THREAD

**Issue by DeDuckProject** [wixplosives/test-drive-react#6]
I'm using trigger.change on the following input:
`<input type='number'>`

`trigger.change`'s new value is a string, so I'm going with the flow and using it like so:
`trigger.change(input, "42");`

and I get the following warning:

`The specified value "42#" is not a valid number. The value must match to the following regular expression...`
Using simulate.change works though...

**Comment by AviVahl** [comment]
`trigger` functionality was removed in v1.0.0.
