### ISSUE TITLE
trigger.change support for checkboxes?

### ISSUE THREAD

**Issue by DeDuckProject** [wixplosives/test-drive-react#7]
I'm trying to simulate a checkbox click using trigger.change.
According to this chunk of code, It seems possible (https://github.com/wix/test-drive-react/blob/9ff45da8e4f5e05c86433fbcfce1c21ef0ba31e7/lib/react-trigger-change.js#L180)

Using a
```jsx
<input type="checkbox"/>
```

and running
```typescript
trigger.change(booleanInput,'true');
```
(only accepted parameter is a string...)

The [above piece of code](https://github.com/wix/test-drive-react/blob/9ff45da8e4f5e05c86433fbcfce1c21ef0ba31e7/lib/react-trigger-change.js#L180) is executed, but event is always fired with event.target.checked=false and never with true.

using: `booleanInput.click();` instead worked though.

**Comment by AviVahl** [comment]
`trigger` functionality was removed in v1.0.0.
